services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P4SSW0RD!
      - TZ=Europe/Amsterdam
    ports:
      - "1433:1433"
    volumes:
      - C:/docker/volumes/sqlserver2022/data:/var/opt/mssql/data